ENH: Centralized Token Replacement
DNNCommunity/Dnn.CommunityForums pull request #1094
Opened 2024-10-02 20:31 UTC by johnhenley

### Description of PR...
Another "year in the making" pull request, this one centralizes token replacement into a single module and entity property accessor methods. Still some more work to do, but 80-90% of the module now using the new token replacement code.

## Changes made
- Supports injection of DNN-standard tokens [USER:\*], [PORTAL:\*], etc. 
![image](https://github.com/user-attachments/assets/888e3ed8-6998-46b1-94b6-b8e234a96e48)
- Adds new [FORUMGROUP:\*], [FORUM:\*], [FORUMUSER:\*], [FORUMTOPIC:\*], and [FORUMPOST:\*] tokens
- Uses DNN-standard `[OBJECT:PROPERTY:{optional length}|{optional format string|{optional replace when empty}]` token syntax
- Uses DNN token replacement API, and supports embedded tokens, so you can inject more meaningful content
- Uses DNN IPropertyAccess API within affected entities ForumInfo, TopicInfo, etc.
![image](https://github.com/user-attachments/assets/7723b947-21f8-4c8a-8e01-81730fa42aa4)
- Delivered `community-default` and `community-bootstrap` templates updated to use new tokens
- On-the-fly mapping of "legacy" Active Forums to appropriate new tokens or DNN-standard tokens (intended for removal by v10)
- Replaced legacy tokens are logged to admin log so admins have visibility and know what needs to be replaced
![image](https://github.com/user-attachments/assets/7bebb570-0f6e-4e83-a3ef-9444246935c9)
- Previously-injected HTML now for legacy tokens moved from C# code to use a resource file, providing designers a way to tweak, and uses the new {optional format string} to inject it (so if a token is replaced with string.Empty, associated/orphaned HTML no longer rendered ![image](https://github.com/user-attachments/assets/3484c683-69a9-4c2d-a06f-d994983884c2)
- Substantial updates to token documentation in wiki (ongoing)
- Adds status tokens for tracking forum and topic status by user (read/unread) (https://github.com/DNNCommunity/Dnn.CommunityForums/wiki/Status-CSS-Class-Tokens)
- Added new resource strings for [RESX:Child]

## How did you test these updates?  

Extensive local testing

## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other
- [ ] Requires documentation updates  
- [ ] I've updated the documentation already  

## Please mark which issue is solved

Close #467 
Close #469 
Close #475 
Close #486 
Close #521 
Close #743

2024-10-11 17:03 UTC, WillStrohl requested changes
@johnhenley This looks great! (and like a ton of work!)  I only caught some minor inline styling that we should probably avoid adding to the solution.  I've CC'd @Timo-Breumelhof for visibility, so we can decide as a group.  😊

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/config/templates/TopicActions.ascx
> +    [FORUMTOPIC:ACTIONDELETEONCLICK|<a href="javascript:void(0)" onclick="{0}" style="vertical-align: middle;" title="[RESX:DeleteTopic]"><i class="fa fa-trash-o fa-fw fa-blue"></i></a>]
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/config/templates/TopicActions.ascx
> +    [FORUMTOPIC:ACTIONDELETEONCLICK|<a href="javascript:void(0)" onclick="{0}" style="vertical-align: middle;" title="[RESX:DeleteTopic]"><i class="fa fa-trash-o fa-fw fa-blue"></i></a>]
There are several instances in this chunk.

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/themes/community-bootstrap/templates/TopicsView.ascx
> +											<td class="dcf-col dcf-col-icon">[FORUM:FORUMICONCSS|<div class="dcf-forum-icon" style="height: 30px; margin-right: 10px;"><i class="fa {0} fa-2x"></i></div>
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/themes/community-default/templates/ForumView.ascx
> +							[FORUM:FORUMICONCSS|<div class="dcf-forum-icon" style="height: 30px; margin-right: 10px;"><i class="fa {0} fa-2x"></i></div>
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
> +                                    [RESX:BY] <i class="fa fa-user fa-blue"></i>&nbsp;[LASTPOSTDISPLAYNAME][FORUMTOPIC:LASTREPLYURL|<a href="{0}" rel="nofollow"><img src="[FORUM:THEMELOCATION]/images
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
> +                            [RESX:BY] <i class="fa fa-user fa-blue"></i>&nbsp;[LASTPOSTDISPLAYNAME][FORUMTOPIC:LASTREPLYURL|<a href="{0}" rel="nofollow"><img src="[FORUM:THEMELOCATION]/images/miniarr
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:03 UTC, WillStrohl commented on Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx
> +								<td class="dcf-col dcf-col-icon">[FORUM:FORUMICONCSS|<div class="dcf-forum-icon" style="height: 30px; margin-right: 10px;"><i class="fa {0} fa-2x"></i></div>
@johnhenley Shouldn't we avoid adding new `style` attributes to the HTML we're adding, and put it into CSS instead? 🤔 CC: @Timo-Breumelhof

2024-10-11 17:07 UTC, johnhenley commented
> @johnhenley This looks great! (and like a ton of work!)  I only caught some minor inline styling that we should probably avoid adding to the solution.  I've CC'd @Timo-Breumelhof for visibility, so we can decide as a group.  😊 

@WillStrohl those are all ascx/templates that reflect "as is" html that was previously injected from c#. I fully expect @Timo-Breumelhof to make another pass in the future to cover that. If that's all, please merge.

2024-10-14 08:05 UTC, Timo-Breumelhof commented
@WillStrohl I agree we should get rid of inline styling. But as it's existing legacy HTML moved to a file, I would prefer to get rid of it in version 9 (as it could potentially break user's styling)

2024-10-14 08:47 UTC, Timo-Breumelhof commented
@WillStrohl @johnhenley  Let's please merge this and create an 8.2 issue for me to fix the CSS?

2024-10-14 23:34 UTC, merged