Implement ModuleSearchBase for enhanced DNN Platform Search
DNNCommunity/Dnn.CommunityForums pull request #131
Opened 2022-03-24 20:22 UTC by johnhenley

### Implements the improved DNN Search experience for Community Forums. 
https://www.dnnsoftware.com/community-blog/cid/154913/Integrating-with-Search-Introducing-ModuleSearchBase
https://www.dnnsoftware.com/community-blog/cid/153947/search-done-right-in-dnn

## Changes made
- Convert TopicsController to implement ModuleSearchBase rather than ISearchable to implement newer search functionality introduced in DNN Platform 7.1.
- If you are using the soft-delete behavior in Community Forums, searches are now incrementally performed based on content update date including marking deleted content as inactive in the search meta data. Otherwise, full rebuild is done at each scheduled search interval.
- If you utilize tags within Community Forums, these will be included in the search metadata.
- View permissions from the forum's security settings are included in the search metadata, so only authorized forum topic viewers should see topics within search results.
- NOTE: In search results, the "source" display name comes from Module's display name, e.g. "Active Forums". If you want to override this, add an entry to ~/DesktopModules/Admin/SearchResults/App_LocalResources/SearchableModules.resx for the Module_[MODULENAME].text, e.g., <data name="Module_Active Forums.Text" xml:space="preserve"><value>Community Forums</value></data>
-  A possible future enhancement might be to write this entry or to perhaps change the module definition ...
			
## PR Template Checklist

- [ ] Fixes Bug
- [X] Feature solution
- [ ] Other

## Please mark which issue is solved

Close #94

2022-03-24 20:26 UTC, johnhenley commented
@WillStrohl Try as I might, I still have some 'git cruft' for you to deal with...for some reason, this pull request pulls in changes from #121 that separated out the Topics.cs into TopicInfo.cs and TopicController.cs. Not sure why. Also, some whitespace issues, but I'm sure you can deal with those. Lastly, since I still don't have a way to separate the SQL updates per pull request, and I still have 3 or 4 of them outstanding, this one includes all of the SQL updates from this pull request as well as the other ones. Let me know if you need help sorting that out.

2022-08-02 21:03 UTC, WillStrohl commented
FYI - I've been trying to use GitHub to attempt to resolve the conflicts so this can be merged, but GitHub crashes every time I try.  :(

2022-08-09 01:07 UTC, WillStrohl requested changes

2022-08-09 01:07 UTC, WillStrohl commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
This update should be using a parameterized query, instead of concatenation. Also, it's missing DNNs (still) required best practice of including the DNN tokens for compatibility with anyone that may be using a different schema (`{databaseOwner}`) or object qualifier (`{objectQualifier]`).

2022-08-09 01:07 UTC, WillStrohl commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
Ideally, a stored procedure would be even better, by the way.  :)

2022-08-09 01:07 UTC, WillStrohl commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
@johnhenley  This is the only major issue I can see with this PR so far...  We shouldn't be concatenating a query like this in the code.  We should be using a SProc instead.  Is that something you'd have the time to update for this PR?  

CC: @Timo-Breumelhof

2022-08-09 01:07 UTC, WillStrohl commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
@johnhenley  Oh... I already said this a while back.  🤦🏽‍♂️😄

2022-08-09 13:47 UTC, johnhenley commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
@WillStrohl 
I literally almost copied that method from the one above it, which also has the same embedded SQL. So I would suggest this is something that should be punted to a new issue and handled with a separate pull request?
![image](https://user-images.githubusercontent.com/9553126/183665492-fd97e711-38ba-4411-93f3-e829c3e97379.png)

2022-08-09 15:28 UTC, WillStrohl commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
Okay. Sounds good to me.  (Meaning, we really should be implementing best practices with any new updates, but that makes sense at this point.)  :)

2022-08-09 15:29 UTC, WillStrohl approved these changes
We'll accept this PR as-is, but it should be noted that we've added to our technical debt with this update.

2022-08-09 15:38 UTC, johnhenley commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
I will create an issue to pay back the debt :)

2022-08-09 15:52 UTC, johnhenley commented on components/Data/Common.cs
> +			string sSQL = "SELECT f.ForumId, ISNULL(CanView,'') as CanView from " + dbPrefix + "Permissions as P INNER JOIN " + dbPrefix + "Forums as f on f.PermissionsID = P.PermissionsId WHERE f.ForumId = "
>  Also, it's missing DNNs (still) required best practice of including the DNN tokens for compatibility with anyone that may be using a different schema (`{databaseOwner}`) or object qualifier (`{objectQualifier]`).

Actually, that accomplished in a round-about way by **_`" + dbPrefix + "`_** part in the concatenated SQL. The dbPrefix comes from:
![image](https://user-images.githubusercontent.com/9553126/183699387-24493003-ec12-4339-94a0-f4b09c95ebb3.png)
which comes from here:
![image](https://user-images.githubusercontent.com/9553126/183699439-24fe18ab-46a2-475f-8f28-bbae6bb064f4.png)

2022-08-09 17:32 UTC, merged